name: Internal Snapshot Publication

on:
  push:
    tags:
      - 'v*'

env:
  ENTANDO_OPT_USE_PPL_TAG: "v1.2.1"
  ENTANDO_OPT_PROJECT_TYPE: "${{ secrets.ENTANDO_OPT_PROJECT_TYPE }}"
  ENTANDO_OPT_FEATURES: "${{ secrets.ENTANDO_OPT_FEATURES }}"
  ENTANDO_OPT_GLOBAL_FEATURES: "${{ secrets.ENTANDO_OPT_GLOBAL_FEATURES }}"
  ENTANDO_OPT_LOG_LEVEL: "${{ secrets.ENTANDO_OPT_LOG_LEVEL }}"
  ENTANDO_OPT_REPO_BOM_URL: "${{ secrets.ENTANDO_OPT_REPO_BOM_URL }}"
  ENTANDO_OPT_CUSTOM_ENV: "${{ secrets.ENTANDO_OPT_CUSTOM_ENV }}"
  PPL_CONTEXT: ${{ toJson(github) }}
  GIT_USER_NAME: "${{ secrets.GIT_USER_NAME }}"
  GIT_USER_EMAIL: "${{ secrets.GIT_USER_EMAIL }}"
  LOCAL_CLONE_DIR: "local-checkout"


jobs:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # INTERNAL PUBLICATION

  internal-publication:
    env:
      ENTANDO_BOT_TOKEN: ${{ secrets.ENTANDO_BOT_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: "PR PIPELINE START"
        id: START
        run: |
          ${{ secrets.ENTANDO_OPT_PPL_INSTALL_CMD }}
          ~/ppl-run \
            .. status-report \
            .. @setup-feature-flags "PR_FORMAT_CHECK" "BOM_CHECK" "BOM" "POST-PUB-TEST" \
          ;
      #~ CHECKOUT
      - name: "CHECKOUT"
        id: CHECKOUT
        run: |
          ~/ppl-run \
            .. checkout-branch --id "CHECKOUT FOR NEXUS PUBLICATION" \
                  --lcd "$LOCAL_CLONE_DIR" \
                  --token "$ENTANDO_BOT_TOKEN" \
            .. pr-preflight-checks --only flags --lcd "$LOCAL_CLONE_DIR" \
          ;
          ~/ppl-run generic GENERATE-BUILD-CACHE-KEY "BUILD_CACHE_KEY" --lcd "$LOCAL_CLONE_DIR" >> $GITHUB_ENV
          ~/ppl-run generic GENERATE-BUILD-TARGET-DIR "BUILD_TARGET_DIR" --lcd "$LOCAL_CLONE_DIR" >> $GITHUB_ENV
      #~ BUILD CACHE
      - name: "Cache Build Dir"
        id: build-cache
        uses: actions/cache@v2
        with:
          path: "${{ env.LOCAL_CLONE_DIR }}/target/"
          key: ${{ runner.os }}-build-${{ env.BUILD_CACHE_KEY }}
      #~ PUBLISH THE ARTIFACT
      - name: "Publish package"
        run: |
          ~/ppl-run generic PUBLISH \
            --id "PUBLICATION" \
            --lcd "$LOCAL_CLONE_DIR"
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      #~ PUBLISH TO DOCKER IMAGE
      - name: "Publish docker"
        env:
          ENTANDO_OPT_DOCKER_BUILDS: "${{ secrets.ENTANDO_OPT_DOCKER_BUILDS }}"
          ENTANDO_OPT_DOCKER_ORG: "${{ secrets.ENTANDO_OPT_DOCKER_ORG }}"
          ENTANDO_OPT_DOCKER_USERNAME: "${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}"
          ENTANDO_OPT_DOCKER_PASSWORD: "${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}"
          ENTANDO_OPT_DOCKER_ALT_LOGIN_URL: "${{ secrets.ENTANDO_OPT_DOCKER_ALT_LOGIN }}"
          ENTANDO_OPT_DOCKER_ALT_USERNAME: "${{ secrets.ENTANDO_OPT_DOCKER_ALT_USERNAME }}"
          ENTANDO_OPT_DOCKER_ALT_PASSWORD: "${{ secrets.ENTANDO_OPT_DOCKER_ALT_PASSWORD }}"
        run: |
          ~/ppl-run docker publish "$ENTANDO_OPT_DOCKER_BUILDS"\
            --id "PUBLISH-DOCKER" \
            --lcd "$LOCAL_CLONE_DIR"

      #~ POST SCAN
      - name: "Post-scan container"
        env:
          SNYK_ORG: "${{ secrets.SNYK_ORG }}"
          SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
        run: |
          ~/ppl-run docker scan "$ENTANDO_OPT_DOCKER_BUILDS"\
            --id "SCAN-DOCKER" \
            --lcd "$LOCAL_CLONE_DIR"
